export const dropdownData = [
    {
      title: "Bags",
      subcategories: {
        "Winter Fashion": [
          "Leather Handbags",
          "Thermal Backpacks",
          "Woolen Tote Bags",
          "Insulated Duffle Bags",
          "Fur-lined Clutches",
        ],
        "Summer Fashion": [
          "Canvas Backpacks",
          "Straw Tote Bags",
          "Beach Handbags",
          "Lightweight Travel Bags",
          "Mesh Gym Bags",
        ],
        "Travel Essentials": [
          "Rolling Suitcases",
          "Carry-on Backpacks",
          "Expandable Duffle Bags",
          "Passport Holders",
          "Packing Cubes",
        ],
        "Luxury Bags": [
          "Designer Handbags",
          "Gold-Trimmed Clutches",
          "Luxury Leather Backpacks",
          "Embroidered Tote Bags",
          "Exclusive Travel Bags",
        ],
        "Casual Bags": [
          "Everyday Backpacks",
          "Simple Tote Bags",
          "Crossbody Bags",
          "Messenger Bags",
          "Convertible Handbags",
        ],
      },
    },
    {
      title: "Clothing",
      subcategories: {
        "Winter Wear": [
          "Woolen Coats",
          "Thermal Jackets",
          "Fleece Sweaters",
          "Puffer Jackets",
          "Snow Pants",
        ],
        "Summer Wear": [
          "Cotton Dresses",
          "Linen Shorts",
          "Sleeveless Tops",
          "Lightweight T-Shirts",
          "Beach Sarongs",
        ],
        "Formal Wear": [
          "Business Suits",
          "Evening Gowns",
          "Dress Shirts",
          "Blazers",
          "Tailored Pants",
        ],
        "Casual Wear": [
          "Denim Jeans",
          "Hoodies",
          "Basic Tees",
          "Leggings",
          "Cargo Pants",
        ],
        Sportswear: [
          "Athletic Shorts",
          "Compression Shirts",
          "Yoga Pants",
          "Running Jackets",
          "Sweatpants",
        ],
      },
    },
    {
      title: "Shoes",
      subcategories: {
        "Winter Shoes": [
          "Snow Boots",
          "Thermal Sneakers",
          "Fur-lined Loafers",
          "Waterproof Hiking Boots",
          "Insulated Slippers",
        ],
        "Summer Shoes": [
          "Flip-Flops",
          "Canvas Sneakers",
          "Strappy Sandals",
          "Espadrilles",
          "Breathable Running Shoes",
        ],
        "Formal Shoes": [
          "Leather Dress Shoes",
          "Oxford Shoes",
          "Heeled Sandals",
          "Brogue Shoes",
          "Patent Loafers",
        ],
        "Casual Shoes": [
          "Slip-on Sneakers",
          "Everyday Flats",
          "Skate Shoes",
          "Canvas Loafers",
          "Suede Moccasins",
        ],
        "Sports Shoes": [
          "Running Shoes",
          "Basketball Sneakers",
          "Soccer Cleats",
          "Tennis Shoes",
          "Trail Running Shoes",
        ],
      },
    },
    {
      title: "Accessories",
      subcategories: {
        "Winter Accessories": [
          "Wool Scarves",
          "Thermal Gloves",
          "Beanie Hats",
          "Fur-lined Mittens",
          "Ear Muffs",
        ],
        "Summer Accessories": [
          "Sun Hats",
          "UV Protection Sunglasses",
          "Beach Towels",
          "Lightweight Scarves",
          "Straw Hats",
        ],
        "Luxury Accessories": [
          "Gold Necklaces",
          "Diamond Rings",
          "Leather Wallets",
          "Silk Ties",
          "Designer Sunglasses",
        ],
        "Casual Accessories": [
          "Everyday Watches",
          "Simple Belts",
          "Basic Sunglasses",
          "Fabric Bracelets",
          "Backpack Charms",
        ],
        "Tech Accessories": [
          "Smartwatch Straps",
          "Wireless Earbuds",
          "Phone Cases",
          "Laptop Sleeves",
          "Charging Cables",
        ],
      },
    },
    {
      title: "Electronics",
      subcategories: {
        "Mobile Devices": [
          "Smartphones",
          "Tablets",
          "E-Readers",
          "Foldable Phones",
          "Rugged Phones",
        ],
        "Laptops & PCs": [
          "Gaming Laptops",
          "Ultrabooks",
          "Desktop Computers",
          "Mini PCs",
          "Workstations",
        ],
        "Audio Devices": [
          "Wireless Headphones",
          "Noise-Canceling Earbuds",
          "Bluetooth Speakers",
          "Home Theater Systems",
          "Turntables",
        ],
        "Wearable Tech": [
          "Smartwatches",
          "Fitness Trackers",
          "AR Glasses",
          "Heart Rate Monitors",
          "VR Headsets",
        ],
        "Gaming Gear": [
          "Gaming Consoles",
          "Mechanical Keyboards",
          "Gaming Mice",
          "VR Controllers",
          "Streaming Webcams",
        ],
      },
    },
    {
      title: "Beauty & Health",
      subcategories: {
        Skincare: [
          "Moisturizers",
          "Sunscreen",
          "Facial Serums",
          "Cleansers",
          "Face Masks",
        ],
        Makeup: ["Foundations", "Lipsticks", "Mascara", "Eyeliners", "Blush"],
        Haircare: [
          "Shampoos",
          "Conditioners",
          "Hair Masks",
          "Hair Dryers",
          "Styling Gels",
        ],
        "Personal Care": [
          "Electric Toothbrushes",
          "Hair Removal Devices",
          "Body Scrubs",
          "Bath Bombs",
          "Deodorants",
        ],
        Wellness: [
          "Essential Oils",
          "Meditation Apps",
          "Sleep Masks",
          "Massage Guns",
          "CBD Products",
        ],
      },
    },
    {
      title: "Home & Kitchen",
      subcategories: {
        Appliances: [
          "Blenders",
          "Microwaves",
          "Dishwashers",
          "Air Fryers",
          "Coffee Machines",
        ],
        Furniture: [
          "Sofas",
          "Dining Tables",
          "Bookshelves",
          "Bed Frames",
          "Office Chairs",
        ],
        Kitchenware: [
          "Cookware Sets",
          "Chef’s Knives",
          "Cutting Boards",
          "Bakeware",
          "Mixing Bowls",
        ],
        "Home Décor": ["Wall Art", "Rugs", "Vases", "Curtains", "Candles"],
        "Storage Solutions": [
          "Closet Organizers",
          "Under-Bed Storage",
          "Pantry Bins",
          "Drawer Dividers",
          "Hanging Racks",
        ],
      },
    },
    {
      title: "Toys & Games",
      subcategories: {
        "Outdoor Toys": [
          "Trampolines",
          "Scooters",
          "Kites",
          "Water Guns",
          "Frisbees",
        ],
        "Board Games": ["Monopoly", "Chess", "Scrabble", "Catan", "Risk"],
        "Educational Toys": [
          "STEM Kits",
          "Coding Toys",
          "Microscopes",
          "Puzzle Sets",
          "Math Flashcards",
        ],
        "Action Figures": [
          "Superhero Figures",
          "Anime Collectibles",
          "Sci-Fi Characters",
          "LEGO Minifigures",
          "Movie Replicas",
        ],
        "Video Games": [
          "PlayStation Games",
          "Xbox Games",
          "Nintendo Switch Games",
          "PC Games",
          "VR Games",
        ],
      },
    },
    {
      title: "Sports & Outdoors",
      subcategories: {
        "Camping Gear": [
          "Tents",
          "Sleeping Bags",
          "Camping Stoves",
          "Hiking Backpacks",
          "Portable Lanterns",
        ],
        "Fitness Equipment": [
          "Dumbbells",
          "Resistance Bands",
          "Treadmills",
          "Yoga Mats",
          "Jump Ropes",
        ],
        "Water Sports": [
          "Kayaks",
          "Snorkeling Gear",
          "Paddleboards",
          "Swim Caps",
          "Diving Fins",
        ],
        Cycling: [
          "Mountain Bikes",
          "Road Bikes",
          "Cycling Helmets",
          "Bike Locks",
          "Water Bottle Holders",
        ],
        "Team Sports": [
          "Basketballs",
          "Football Cleats",
          "Soccer Jerseys",
          "Baseball Bats",
          "Hockey Sticks",
        ],
      },
    },
  ];